version: "3.7"
services:
  app:
    build:
      args:
        user: ${FPM_USER}
        uid: ${FPM_UID}
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /var/www/laravel/
    volumes:
      - ./:/var/www
      - ./docker-compose/xdebug/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - laravel-network
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - PHP_IDE_CONFIG=serverName=${APP_URL}

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/var/lib.mysql
    networks:
      - laravel-network
    ports:
      - "3306:3306"
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
